#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02
apt-get update
apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.0 -y
apt-get install haproxy -y
sed -i "/errors\/504.http/a listen http-incoming\n\tmode http\n\tbalance roundrobin\n\tbind :80\n\toption forwardfor\n\tserver 199774-web-01 35.175.104.197\n\tserver 199774-web-02 100.25.181.13" /etc/haproxy/haproxy.cfg
service haproxy start
