#!/usr/bin/env bash

# Install Nginx if not already installed
if ! command -v nginx &> /dev/null; then
    sudo apt update
    sudo apt install nginx
fi

# Check and update Nginx configuration
sudo sed -i '/include \/etc\/nginx\/conf.d\/\*\.conf;/a listen 80;' /etc/nginx/nginx.conf
sudo sed -i '/^listen\s*80;$/d' /etc/nginx/conf.d/default.conf
echo "listen 80;" | sudo tee -a /etc/nginx/conf.d/default.conf

# Restart Nginx
sudo service nginx restart
