#!/usr/bin/env bash

cp /etc/hosts ~/hosts.new

# Replace localhost in /etc/hosts file
sed -i 's/^127.0.0.1.*localhost/127.0.0.2    localhost/' /etc/hosts

# Add Facebook to /etc/hosts file
echo "8.8.8.8    facebook.com" >> /etc/hosts

cp -f ~/hosts.new /etc/hosts
