#!/usr/bin/env bash
# Fix by installing apache and changing output to hello holberton
sudo apt-get install apache2 -y
sudo systemctl start apache2
echo "Hello Holberton" > /var/www/html/index.html
echo "ServerName localhost" >> /etc/apache2/apache2.conf
