#!/bin/env bash
#  reload gunicorn server gracefully
pkill -HUP gunicorn

if pgrep -x "gunicorn" > /dev/null; then
    echo "Gunicorn reloaded successfully."
else
    echo "Gunicorn reload failed."
fi
